Repository UCL/STIR, pull requests merged in 2024-02, with the labels that each got.

#1359 Add stir_list_registries utility
  documentation/STIR-UsersGuide.tex
  documentation/release_6.0.htm
  src/recon_buildblock/recon_buildblock_registries.cxx
  src/utilities/CMakeLists.txt
  src/utilities/stir_list_registries.cxx
Labels: enhancement

#1382 fix Interfile parsing for projdata
  src/IO/InterfileHeader.cxx
Labels: bug

#1375 Axial bucket projection issue
  documentation/release_6.1.htm
  src/buildblock/GeometryBlocksOnCylindrical.cxx
  src/buildblock/Scanner.cxx
  src/recon_test/CMakeLists.txt
  src/recon_test/test_blocks_on_cylindrical_projectors.cxx
  src/recon_test/test_geometry_blocks_on_cylindrical.cxx
  src/test/test_interpolate_projdata.cxx
Labels: bug, help wanted
