Repository UCL/STIR, pull requests merged in 2024-11, with the labels that each got.

#1536 Improve CMake library dependencies
  src/IO/CMakeLists.txt
  src/cmake/STIRConfig.cmake.in
  src/recon_buildblock/CMakeLists.txt
Labels: enhancement

#1531 Fix SSRB for ACFs in scatter estimation
  documentation/release_6.3.htm
  src/include/stir/scatter/ScatterEstimation.h
  src/scatter_buildblock/ScatterEstimation.cxx
Labels: bug

#1542 Change bins in mask for sinogram message to use info()
  src/scatter_buildblock/CreateTailMaskFromACFs.cxx
Labels: bug, enhancement
